#!/usr/bin/env python3
"""Build a deterministic, readable, standalone Python file using only the stdlib."""

import argparse
import hashlib
from pathlib import Path
import tomllib


ROOT = Path(__file__).resolve().parents[1]
BOOTSTRAP = '''#!/usr/bin/env python3
# AutoCD standalone distribution. Generated by tools/build_single.py.
import sys
if sys.version_info < (3, 11):
    raise SystemExit("AutoCD requires Python 3.11 or later.")
import importlib.abc
import importlib.util
import linecache

sys._autocd_artifact = __file__
'''
LOADER = '''
class _AutoCDLoader(importlib.abc.MetaPathFinder, importlib.abc.Loader):
    def find_spec(self, fullname, path=None, target=None):
        if fullname in _SOURCES:
            return importlib.util.spec_from_loader(fullname, self, is_package=fullname == "autocd")

    def create_module(self, spec):
        return None

    def exec_module(self, module):
        source = _SOURCES[module.__name__]
        filename = "<bundled/" + module.__name__.replace(".", "/") + ".py>"
        module.__file__ = filename
        linecache.cache[filename] = (len(source), None, source.splitlines(True), filename)
        exec(compile(source, filename, "exec"), module.__dict__)

sys.meta_path.insert(0, _AutoCDLoader())
if __name__ == "__main__":
    from autocd.cli import main
    raise SystemExit(main())
'''


def build(output):
    modules = {}
    for path in sorted((ROOT / "src/autocd").glob("*.py")):
        name = "autocd" if path.stem == "__init__" else f"autocd.{path.stem}"
        source = path.read_text(encoding="utf-8")
        compile(source, str(path), "exec")
        modules[name] = source
    namespace = {}
    exec(modules["autocd"], namespace)
    metadata = tomllib.loads((ROOT / "pyproject.toml").read_text())
    if namespace["__version__"] != metadata["project"]["version"]:
        raise SystemExit("Version mismatch between package and pyproject.toml")
    parts = [BOOTSTRAP, "\n_SOURCES = {\n"]
    for name, source in sorted(modules.items()):
        parts.append(f"    {name!r}: (\n")
        parts.extend(f"        {line!r}\n" for line in source.splitlines(keepends=True))
        parts.append("    ),\n")
    parts.extend(["}\n", LOADER])
    content = "".join(parts)
    compile(content, str(output), "exec")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8", newline="\n")
    output.chmod(0o755)
    checksum = hashlib.sha256(output.read_bytes()).hexdigest()
    (output.parent / "SHA256SUMS").write_text(f"{checksum}  {output.name}\n", encoding="ascii")
    return checksum


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "dist/autocd.py")
    args = parser.parse_args()
    checksum = build(args.output)
    print(f"{args.output} · SHA256 {checksum}")
